USE [master]
GO

/****** Object:  Database [PM]    Script Date: 5/2/2017 9:47:17 AM ******/
CREATE DATABASE [PM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PM', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PM_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PM_log.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PM] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PM] SET ARITHABORT OFF 
GO

ALTER DATABASE [PM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PM] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PM] SET  MULTI_USER 
GO

ALTER DATABASE [PM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PM] SET  READ_WRITE 
GO


